<<<<<<< HEAD
baseurl = "https://helengraham.netlify.com/"
title = "Helen Graham"
theme = "hugo-creative-portfolio-theme"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "sea"
  description = "Helen's data science blog"
  copyright = "&copy;2018 Helen Graham"
  sidebarAbout = [
    "Aspiring data scientist and cheesecake enthusiast"
  ]
  # Contact page
     # Since this template is static, the contact form uses www.formspree.io as a
     # proxy. The form makes a POST request to their servers to send the actual
     # email. Visitors can send up to a 1000 emails each month for free.
     #
     # What you need to do for the setup?
     #
     # - set your email address under 'email' below
     # - upload the generated site to your server
     # - send a dummy email yourself to confirm your account
     # - click the confirm link in the email from www.formspree.io
     # - you're done. Happy mailing!
  email = "hello@helengraham.uk"

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Home"
  url = "post/"
  home = true

  [[params.navlinks]]
  name = "About"
  url = "about/"

  #[[params.navlinks]]
  #name = "Get in touch"
  #url = "contact/"

  [params.social]
  #facebook      = "full page or profile url in facebook"
  #googleplus    = "full profile url in googleplus"
  email         = "hello@helengraham.uk"
  twitter       = "https://www.twitter.com/helngram"
  #linkedin      = "full profile url in linkedin"
  #stackoverflow = "full profile url in stackoverflow"
  #instagram     = "full profile url in instagram"
  github        = "https://github.com/heg31"
  #youtube       = "full profile url in youtube" 
=======
baseurl = "https://helengraham.netlify.com/"
title = "Helen Graham"
theme = "hugo-creative-portfolio-theme"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "sea"
  description = "Helen's data science blog"
  copyright = "&copy;2018 Helen Graham"
  sidebarAbout = [
    "Aspiring data scientist and cheesecake enthusiast"
  ]
  # Contact page
     # Since this template is static, the contact form uses www.formspree.io as a
     # proxy. The form makes a POST request to their servers to send the actual
     # email. Visitors can send up to a 1000 emails each month for free.
     #
     # What you need to do for the setup?
     #
     # - set your email address under 'email' below
     # - upload the generated site to your server
     # - send a dummy email yourself to confirm your account
     # - click the confirm link in the email from www.formspree.io
     # - you're done. Happy mailing!
  email = "hello@helengraham.uk"

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Home"
  url = "post/"
  home = true

  [[params.navlinks]]
  name = "About"
  url = "about/"

  #[[params.navlinks]]
  #name = "Get in touch"
  #url = "contact/"

  [params.social]
  #facebook      = "full page or profile url in facebook"
  #googleplus    = "full profile url in googleplus"
  email         = "hello@helengraham.uk"
  twitter       = "https://www.twitter.com/helngram"
  #linkedin      = "full profile url in linkedin"
  #stackoverflow = "full profile url in stackoverflow"
  #instagram     = "full profile url in instagram"
  github        = "https://github.com/heg31"
  #youtube       = "full profile url in youtube" 
>>>>>>> master
